language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get -qq install qt5-default qt59base qt59declarative libqt5svg5-dev qttools5-dev qttools5-dev-tools

script:
    - /opt/qt59/bin/qmake
    - make